openapi: 3.0.3
info:
  title: >-
    SafeStorageInternal
  version: v1.0
  license:
    name: PN software license
    url: 'https://www.pn.pagopa.it/LICENSE'
  description: >-
    __SafeStorageInternal__: CRUD interne

servers:
  - url: >-
      https://api.pn.pagopa.it
    description: Server url
tags:
  - name: docTypeInternal
    description: Tipo Documento
  - name: documentInternal
    description: Documenti
  - name: scadenzaDocumentiInternal
    description: Scadenza documenti
  - name: userConfigurationInternal
    description: Anagrafica Client
  - name: tagsInternal
    description: Tags
paths:

  ################################################################################################
  ###                                      CONFIGURAZIONI                                      ###
  ################################################################################################
  '/safestorage/internal/v1/doctypes/{typeId}':
    get:
      operationId: getDocType
      summary: Restituisce una tipologia di documento.
      tags:
        - docTypeInternal
      parameters:
        - $ref: '#/components/parameters/typeId'
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/doctypes/_PN_TEST_
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentTypeResponse'
              example:
                docType: null
                error:
                  code: null
                  description: DocumentType with id _PN_TEST_ not found
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentTypeResponse'
              example:
                docType:
                  tipoDocumento: PN_NOTIFICATION_ATTACHMENTS
                  checksum: SHA256
                  initialStatus: PRELOADED
                  statuses:
                    PRELOADED:
                      allowedStatusTransitions: [ATTACHED]
                      storage: PN_TEMPORARY_DOCUMENT
                      technicalState: available
                    ATTACHED:
                      allowedStatusTransitions: []
                      storage: PN_NOTIFIED_DOCUMENTS
                      technicalState: attached
                  informationClassification: C
                  digitalSignature: false
                  timeStamped: NONE
    put:
      operationId: updateDocType
      summary: Aggiorna una tipologia di documento.
      tags:
        - docTypeInternal
      parameters:
        - $ref: '#/components/parameters/typeId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentType'
        required: true
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/doctypes/_PN_TEST_
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentTypeResponse'
              example:
                docType: null
                error:
                  code: null
                  description: DocumentType with id _PN_TEST_ not found
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentTypeResponse'
    delete:
      operationId: deleteDocType
      summary: Elimina una tipologia di documento.
      tags:
        - docTypeInternal
      parameters:
        - $ref: '#/components/parameters/typeId'
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/doctypes/_PN_TEST_
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentTypeResponse'
              example:
                docType: null
                error:
                  code: null
                  description: DocumentType with id _PN_TEST_ not found
        '204':
          description: OK

  '/safestorage/internal/v1/doctypes':
    post:
      operationId: insertDocType
      summary: Inserisce una nuova tipologia di documento.
      tags:
        - docTypeInternal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentType'
      responses:
        '400':
          description: >-
            #### Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentTypeResponse'
              example:
                docType: null
                error:
                  code: null
                  description: The attribute tipoDocumento is null
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safe-storage/v1/configurations/documents-types
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '409':
          description: Conflict
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentTypeResponse'

  '/safestorage/internal/v1/documents/{documentKey}':
    get:
      operationId: getDocument
      summary: Restituisce un documento.
      tags:
        - documentInternal
      parameters:
        - $ref: '#/components/parameters/documentKey'
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/documents/DOCUMENT_TEST
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
              example:
                docType: null
                error:
                  code: null
                  description: Document with id DOCUMENT_TEST not found
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
    patch:
      operationId: patchDoc
      summary: Aggiorna un documento.
      tags:
        - documentInternal
      parameters:
        - $ref: '#/components/parameters/documentKey'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentChanges'
        required: true
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/documents/DOCUMENT_TEST
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
              example:
                docType: null
                error:
                  code: null
                  description: Document with id DOCUMENT_TEST not found
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
    delete:
      operationId: deleteDocument
      summary: Elimina un documento.
      tags:
        - documentInternal
      parameters:
        - $ref: '#/components/parameters/documentKey'
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/documents/DOCUMENT_TEST
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
              example:
                docType: null
                error:
                  code: null
                  description: Document with id DOCUMENT_TEST not found
        '204':
          description: OK

  '/safestorage/internal/v1/documents':
    post:
      operationId: insertDocument
      summary: Inserisce una nuovo documento.
      tags:
        - documentInternal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentInput'
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/documents
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'

  '/safestorage/internal/v1/scadenza-documenti':
    post:
      operationId: insertOrUpdateScadenzaDocumenti
      summary: Inserisce una nuova scadenza documenti.
      tags:
        - scadenzaDocumentiInternal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScadenzaDocumentiInput'
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/scadenza-documenti
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScadenzaDocumentiResponse'

  '/safestorage/internal/v1/userConfigurations/{name}':
    get:
      operationId: getUserConfiguration
      summary: Restituisce una anagrafica client.
      tags:
        - userConfigurationInternal
      parameters:
        - $ref: '#/components/parameters/name'
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/userConfigurations/TEST_CLIENT
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
              example:
                docType: null
                error:
                  code: null
                  description: Client id CLIENT_TEST not found
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConfigurationResponse'
    patch:
      operationId: patchUserConfiguration
      summary: Aggiorna una anagrafica client.
      tags:
        - userConfigurationInternal
      parameters:
        - $ref: '#/components/parameters/name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserConfigurationChanges'
        required: true
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/userConfigurations/TEST_CLIENT
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
              example:
                docType: null
                error:
                  code: null
                  description: Client id CLIENT_TEST not found
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConfigurationResponse'
    delete:
      operationId: deleteUserConfiguration
      summary: Elimina una anagrafica client.
      tags:
        - userConfigurationInternal
      parameters:
        - $ref: '#/components/parameters/name'
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/userConfigurations/TEST_CLIENT
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
              example:
                docType: null
                error:
                  code: null
                  description: Client id CLIENT_TEST not found
        '204':
          description: OK

  '/safestorage/internal/v1/userConfigurations':
    post:
      operationId: insertUserConfiguration
      summary: Inserisce una nuova anagrafica client.
      tags:
        - userConfigurationInternal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserConfiguration'
      responses:
        '400':
          description: >-
            #### Bad request
        '401':
          description: >-
            #### Unauthorized
              - __x-api-key__ e/o __x-pagopa-safestorage-cx-id__ assenti
        '403':
          description: >-
            #### Forbidden
              - Invalid __x-api-key__
          content:
            application/json:
              example:
                timestamp: 2023-02-21T10:24:06.294+00:00
                path: /safestorage/internal/v1/userConfigurations/TEST_CLIENT
                status: 403
                error: Forbidden
                message: Invalid x-api-key
                requestId: cdf95798-11
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConfigurationResponse'

  '/safestorage/internal/v1/tags/{tagKeyValue}':
    get:
      operationId: getTagsRelations
      summary: Restituisce una serie di fileKey associate ad una singola coppia chiave-valore di un tag
      tags:
        - tagsInternal
      parameters:
        - $ref: '#/components/parameters/tagKeyValue'
      responses:
        '400':
          description: >-
            #### Bad request
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagsRelationsResponse'
              example:
                tagsDto: null
                error:
                  code: 404
                  description: Tags with key _TEST not found
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagsRelationsResponse'

  '/safestorage/internal/v1/documents/{documentKey}/tags':
    put:
      operationId: putTags
      summary: Aggiorna i tag associati ad un documento nella tabella pn-SsDocumenti e le associazioni chiave-valore nella tabella pn-SsTags
      tags:
        - tagsInternal
      parameters:
        - $ref: '#/components/parameters/documentKey'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagsChanges'
      responses:
        '400':
          description: >-
            #### Bad request
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagsResponse'

components:
  parameters:
    typeId:
      name: typeId
      description: Identificativo del tipo di documento
      in: path
      required: true
      schema:
        type: string
    documentKey:
      name: documentKey
      description: Identificativo del documento
      in: path
      required: true
      schema:
        type: string
    name:
      name: name
      description: Nome del client
      in: path
      required: true
      schema:
        type: string
    tagKeyValue:
        name: tagKeyValue
        description: Associazione chiave-valore del tag
        in: path
        required: true
        schema:
            type: string

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    DocumentType:
      type: object
      properties:
        tipoDocumento:
          type: string
          description: nome del tipo di documento
        checksum:
          description: >-
            codice di verifica del corretto caricamento del file
            https://aws.amazon.com/it/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/
          type: string
          enum: [ 'MD5', 'SHA256', 'NONE']
        initialStatus:
          type: string
        statuses:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CurrentStatus'
        informationClassification:
          description: >-
            * `C` - Confidential
            * `HC`- Highly Confidential </br>
            Se il valore è HC il file deve essere criptato.</br>
            See [information classification](https://pagopa.atlassian.net/wiki/spaces/EN/pages/357204284/Data+Classification+Handling#Classificazione)
          type: string
          enum: [ 'C', 'HC' ]
        transformations:
          type: array
          items:
            type: string
            enum: ['NONE', 'SIGN', 'SIGN_AND_TIMEMARK', 'RASTER', 'DUMMY']
        timeStamped:
          type: string
          enum: [ 'NONE', 'STANDARD' ]
    CurrentStatus:
      type: object
      properties:
        allowedStatusTransitions:
          $ref: '#/components/schemas/AllowedStatusTransitions'
        storage:
          $ref: '#/components/schemas/Storage'
        technicalState:
          $ref: '#/components/schemas/TechnicalState'
    Storage:
      type: string
    AllowedStatusTransitions:
      type: array
      items:
        type: string
    TechnicalState:
      type: string
    DocumentTypeResponse:
      type: object
      properties:
        docType:
          $ref: '#/components/schemas/DocumentType'
        error:
          $ref: '#/components/schemas/Error'
    Document:
      type: object
      properties:
        documentKey:
          type: string
        documentState:
          type: string
        documentLogicalState:
          type: string
        clientShortCode:
          type: string
        retentionUntil:
          description: >-
            data di scadenza del file
          type: string
        checkSum:
          description:
            valore ottenuto dal calcolo della chiave hashing dell’oggetto
          type: string
        contentLenght:
          type: number
        contentType:
          type: string
        documentType:
          $ref: '#/components/schemas/DocumentType'
        lastStatusChangeTimestamp:
          type: string
          format: date-time
          description: >-
            Timestamp dell'ultima variazione di stato del documento.
        tags:
          type: object
          additionalProperties:
              type: array
              items:
                type: string


    DocumentInput:
      allOf:
        - $ref: '#/components/schemas/Document'
        - type: object
          properties:
            documentType:
              type: string
    DocumentResponse:
      type: object
      properties:
        document:
          allOf:
            - $ref: '#/components/schemas/Document'
            - type: object
              properties:
                documentType:
                  $ref: '#/components/schemas/DocumentType'
        error:
          $ref: '#/components/schemas/Error'
    ScadenzaDocumenti:
      type: object
      properties:
        documentKey:
          type: string
        retentionUntil:
          type: integer
          format: int64
    ScadenzaDocumentiInput:
        type: object
        properties:
          documentKey:
            type: string
          retentionUntil:
            type: integer
            format: int64
    ScadenzaDocumentiResponse:
      type: object
      properties:
        scadenzaDocumenti:
          allOf:
            - $ref: '#/components/schemas/ScadenzaDocumenti'
        error:
          $ref: '#/components/schemas/Error'
    DocumentChanges:
      type: object
      properties:
        documentState:
          type: string
        retentionUntil:
          description: >-
            data di scadenza del file
          type: string
        checkSum:
          description:
            valore ottenuto dal calcolo della chiave hashing dell’oggetto
          type: string
        contentLenght:
          type: number
        lastStatusChangeTimestamp:
          type: string
          format: date-time
          description: >-
            Timestamp dell'ultima variazione di stato del documento.
    UserConfiguration:
      type: object
      properties:
        name:
          type: string
        apiKey:
          type: string
        canCreate:
          type: array
          items:
            type: string
          description: Elenco dei tipi di documenti che il client è autorizzato a creare.
        canRead:
          type: array
          items:
            type: string
          description: Elenco dei tipi di documenti che il client è autorizzato a leggere.
        canModifyStatus:
          type: array
          items:
            type: string
          description: Elenco dei tipi di documenti che il client è autorizzato a modificare.
        canWriteTags:
          type: boolean
          description: Definisce se il client è autorizzato a scrivere i tag.
        canReadTags:
            type: boolean
            description: Definisce se il client è autorizzato a leggere i tag.
        canExecutePatch:
          type: boolean
        signatureInfo:
          type: string
        destination:
          type: object
          description: Informazioni per contattare in modalità push i sistemi client.
          properties:
            sqsUrl:
              type: string
              description: URL della coda SQS a cui contattare il client
    UserConfigurationResponse:
      type: object
      properties:
        userConfiguration:
          $ref: '#/components/schemas/UserConfiguration'
        error:
          $ref: '#/components/schemas/Error'

    UserConfigurationChanges:
      type: object
      properties:
        canCreate:
          type: array
          items:
            type: string
          description: Elenco dei tipi di documenti che il client è autorizzato a creare.
        canRead:
          type: array
          items:
            type: string
          description: Elenco dei tipi di documenti che il client è autorizzato a leggere.
        canWriteTags:
          type: boolean
          description: Definisce se il client è autorizzato a scrivere i tag.
        canReadTags:
            type: boolean
            description: Definisce se il client è autorizzato a leggere i tag.
        canModifyStatus:
          type: array
          items:
            type: string
          description: Elenco dei tipi di documenti che il client è autorizzato a modificare.
        apiKey:
          type: string
        signatureInfo:
          type: string

    TagsRelationsDto:
      type: object
      properties:
        tagKeyValue:
          type: string
        fileKeys:
          type: array
          items:
            type: string

    TagsDto:
      type: object
      properties:
        tags:
          type: object
          additionalProperties:
            type: array
            items:
              type: string

    TagsChanges:
      type: object
      properties:
        SET:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Tags to be set
        DELETE:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Tags to be deleted
      required:
        - fileKey

    TagsRelationsResponse:
      type: object
      properties:
        tagsRelationsDto:
          $ref: '#/components/schemas/TagsRelationsDto'
        error:
          $ref: '#/components/schemas/Error'

    TagsResponse:
      type: object
      properties:
        tagsDto:
          $ref: '#/components/schemas/TagsDto'
        error:
          $ref: '#/components/schemas/Error'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

security:
  - ApiKeyAuth: [] # use the same name as under securitySchemes
